changed readme to new Python dependency manager
MrTeferi/MTG-Art-Downloader pull request #4
Opened 2022-08-12 10:51 UTC by LeducH

2022-08-15 17:21 UTC, MrTeferi requested changes
Thanks for the PR, if we make these changes I think we're good to go!

2022-08-15 17:21 UTC, MrTeferi commented on README.md
> +[1]: https://python-poetry.org/docs/basic-usage/
Need to add blank line at the end so we can pass pre-commit check

2022-08-15 17:21 UTC, MrTeferi commented on README.md
> +We now use `poetry` as package manager [link][1]
Maybe add a colon after manager here :)

2022-08-15 17:21 UTC, MrTeferi commented on README.md
> +- executed it with
executed > execute

2022-08-15 18:55 UTC, LeducH commented
Hey, cool looks good.

2022-08-27 11:37 UTC, HelixVita commented
https://github.com/MrTeferi/MTG-Art-Downloader/issues/5

2022-08-27 12:04 UTC, HelixVita requested changes
Not everybody knows what Python Poetry is, and pointing the user to the docs might make it seem unnecessarily complicated to install, when really it's just `scoop install poetry` and you're done.

Then again maybe not everyone uses scoop. But I figure that's exceedingly unlikely if you're a coder _and_ you're on Windows.

2022-08-27 12:04 UTC, HelixVita commented on README.md
> +```
```suggestion
- Download this repository `git clone https://github.com/MrTeferi/MTG-Art-Downloader`
- If you don't have Python Poetry, simply install it with `scoop install poetry` or read more at ([link][1])
- Install dependencies `poetry install`
```

2022-08-29 02:43 UTC, merged